version: "3.3"

services:
  postgres:
    image: postgres:14.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker-config:/docker-entrypoint-initdb.d